config/routes.rb
Rails.application.routes.draw do
  
  get 'password_resets/new'

  get 'password_resets/edit'

  resources :users, except: [:index] do
  resources :appointments, except: [:index, :show, :delete]
  delete "/appointments/:workout_id/:day", to: "appointments#destroy"
  end

  # users
  get "/me/:username", to: "users#show", as: "profile"
  get "/signup", to: "users#new", as: "signup"
  post "/signup", to: "users#create"
  get "/logout", to: "sessions#destroy", as: "logout"
  
  #auth routes
  get "/signup" => "users#new"

  # workouts
  resources :workouts, only: [:index, :show]

  # musclegroups
  root "musclegroups#index"
  get "/muscle/:name", to: "musclegroups#show", as: "muscle"

  # sessions
  get "/login", to: "sessions#new", as: "login"
  post "/login", to: "sessions#create"

  #password reset

  get '/password_resets/new', to: "password_resets#new"
  post '/password_resets', to: "password_resets#create"
  get '/password_resets/:token/edit', to: "password_resets#edit"
  patch '/password_resets/:token', to: "password_resets#update"
 
  resources :password_resets,     only: [:new, :create, :edit, :update]

end

# Prefix Verb   URI Pattern                                     Controller#Action
#   password_resets_new GET    /password_resets/new(.:format)                  password_resets#new
#  password_resets_edit GET    /password_resets/edit(.:format)                 password_resets#edit
#     user_appointments POST   /users/:user_id/appointments(.:format)          appointments#create
#  new_user_appointment GET    /users/:user_id/appointments/new(.:format)      appointments#new
# edit_user_appointment GET    /users/:user_id/appointments/:id/edit(.:format) appointments#edit
#      user_appointment PATCH  /users/:user_id/appointments/:id(.:format)      appointments#update
#                       PUT    /users/:user_id/appointments/:id(.:format)      appointments#update
#                       DELETE /users/:user_id/appointments/:id(.:format)      appointments#destroy
#                 users POST   /users(.:format)                                users#create
#              new_user GET    /users/new(.:format)                            users#new
#             edit_user GET    /users/:id/edit(.:format)                       users#edit
#                  user GET    /users/:id(.:format)                            users#show
#                       PATCH  /users/:id(.:format)                            users#update
#                       PUT    /users/:id(.:format)                            users#update
#                       DELETE /users/:id(.:format)                            users#destroy
#               profile GET    /me/:username(.:format)                         users#show
#                signup GET    /signup(.:format)                               users#new
#                       POST   /signup(.:format)                               users#create
#                logout GET    /logout(.:format)                               sessions#destroy
#                       GET    /signup(.:format)                               users#new
#              workouts GET    /workouts(.:format)                             workouts#index
#               workout GET    /workouts/:id(.:format)                         workouts#show
#                  root GET    /                                               musclegroups#index
#                muscle GET    /muscle/:name(.:format)                         musclegroups#show
#                 login GET    /login(.:format)                                sessions#new
#                       POST   /login(.:format)                                sessions#create
#                       GET    /password_resets/new(.:format)                  password_resets#new
#       password_resets POST   /password_resets(.:format)                      password_resets#create
#    new_password_reset GET    /password_resets/new(.:format)                  password_resets#new
#   edit_password_reset GET    /password_resets/:id/edit(.:format)             password_resets#edit
#        password_reset PATCH  /password_resets/:id(.:format)                  password_resets#update
#                       PUT    /password_resets/:id(.:format)                

app/models/musclegroup.rb
class Musclegroup < ActiveRecord::Base
  has_many :foods
  has_many :supplements
  has_many :workouts



  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/controllers/musclegroups_controller.rb
class MusclegroupsController < ApplicationController
  def index
    @muscles = Musclegroup.all
  end

  def show
    @muscle = Musclegroup.friendly.find_by_name(params[:name])
  end
end

app/helpers/musclegroups_helper.rb
module MusclegroupsHelper
end

app/views/musclegroups/index.html.erb
<h1 class="cvp">Meet Leo. The elegant excerise app ...</h1>
<h4 class="cvp-sub">Choose a muscle group you'd like to work out</h4>

<!-- LEO! -->
<div id="box-wrapper">

	<!-- leo -->
	<div id="leo">
 		<%= image_tag "muscles-body-02-02.png", style: "width: 150%" %>
	</div>

	<!-- biceps -->
	<a href="<%= muscle_path(@muscles[4].name) %>">
		<div id="bicep-l" class="animated bounceInDown biceps">
			<%= image_tag "muscles-body-02-bicep-l-03.svg", style: "width: 100%" %>
		</div>
	</a>
	<a href="<%= muscle_path(@muscles[4].name) %>">
		<div id="bicep-r" class="animated bounceInDown biceps">
			<%= image_tag "muscles-body-02-bicep-r-10.svg", style: "width: 100%" %>
		</div>
	</a>

	<!-- delts -->
	<a href="<%= muscle_path("Deltoids") %>">
		<div id="delt-l" class="animated bounceInDown delts">
			<%= image_tag "muscles-body-02-delt-l-05.svg", style: "width: 100%" %>
		</div>
	</a>
	<a href="<%= muscle_path("Deltoids") %>">
		<div id="delt-r" class="animated bounceInDown delts">
			<%= image_tag "muscles-body-02-delt-r-11.svg", style: "width: 100%" %>
		</div>
	</a>

	<!-- obliques -->
	<a href="<%= muscle_path("Obliques") %>">
		<div id="obliques" class="animated bounceInDown">
			<%= image_tag "muscles-body-02-obliques-04-07.svg", style: "width: 100%" %>
		</div>
	</a>

	<!-- pecs -->
	<a href="<%= muscle_path("Pectorals") %>">
		<div id="pecs" class="animated bounceInDown">
			<%= image_tag "muscles-body-02-pec-04.svg", style: "width: 100%" %>
		</div>
	</a>

	<!-- abs -->
	<a href="<%= muscle_path("Abdominals") %>">
		<div id="abs" class="animated bounceInDown">
			<%= image_tag "muscles-body-02-abs-06.svg", style: "width: 100%" %>
		</div>
	</a>
	
	<!-- traps -->
	<a href="<%= muscle_path("Trapezius") %>">
		<div id="traps" class="animated bounceInDown">
			<%= image_tag "muscles-body-02-traps-08.svg", style: "width: 100%" %>
		</div>
	</a>

	<!-- quads -->
	<a href="<%= muscle_path("Quadriceps") %>">
		<div id="quads" class="animated bounceInDown">
			<%= image_tag "muscles-body-02-quads-09.svg", style: "width: 100%" %>
		</div>
	</a>

	<!-- tibias -->
	<a href="<%= muscle_path("Tibialis Anterior") %>">
		<div id="tibia-l" class="animated bounceInDown tibias">
			<%= image_tag "muscles-body-02-tibia-l-12.svg", style: "width: 100%" %>
		</div>
	</a>

	<a href="<%= muscle_path("Tibialis Anterior") %>">
		<div id="tibia-r" class="animated bounceInDown tibias">
			<%= image_tag "muscles-body-02-tibia-r-13.svg", style: "width: 100%" %>
		</div>
	</a>

	<!-- forearms -->
	<a href="<%= muscle_path("Forearms") %>">
		<div id="forearm-l" class="animated bounceInDown forearms">
			<%= image_tag "muscles-body-02-forearm-l-14.svg", style: "width: 100%" %>
		</div>
	</a>

	<a href="<%= muscle_path("Forarms") %>">
		<div id="forearm-r" class="animated bounceInDown forearms">
			<%= image_tag "muscles-body-02-forearm-r-15.svg", style: "width: 100%" %>
		</div>
	</a>

</div>

	<div class="quick-view animated fadeIn" id="quick-view-abs" hidden>
		<h3><%= @muscles[1].name %></h3>
		<p><%= @muscles[1].description %></p>
		<a>Click muscle group to read more...</a>
	</div>

	<div class="quick-view animated fadeIn" id="quick-view-biceps" hidden>
		<h3><%= @muscles[4].name %></h3>
		<p><%= @muscles[4].description %></p>
		<a>Click muscle group to read more...</a>
	</div>

	<div class="quick-view animated fadeIn" id="quick-view-delts" hidden>
		<h3><%= @muscles[6].name %></h3>
		<p><%= @muscles[6].description %></p>
		<a>Click muscle group to read more...</a>
	</div>

	<div class="quick-view animated fadeIn" id="quick-view-pecs" hidden>
		<h3><%= @muscles[5].name %></h3>
		<p><%= @muscles[5].description %></p>
		<a>Click muscle group to read more...</a>
	</div>

	<div class="quick-view animated fadeIn" id="quick-view-obliques" hidden>
		<h3><%= @muscles[0].name %></h3>
		<p><%= @muscles[0].description %></p>
		<a>Click muscle group to read more...</a>
	</div>

	<div class="quick-view animated fadeIn" id="quick-view-traps" hidden>
		<h3><%= @muscles[3].name %></h3>
		<p><%= @muscles[3].description %></p>
		<a>Click muscle group to read more...</a>
	</div>

	<div class="quick-view animated fadeIn" id="quick-view-quads" hidden>
		<h3><%= @muscles[2].name %></h3>
		<p><%= @muscles[2].description %></p>
		<a>Click muscle group to read more...</a>
	</div>

	<div class="quick-view animated fadeIn" id="quick-view-tibias" hidden>
		<h3><%= @muscles[8].name %></h3>
		<p><%= @muscles[8].description %></p>
		<a>Click muscle group to read more...</a>
	</div>

	<div class="quick-view animated fadeIn" id="quick-view-forearms" hidden>
		<h3><%= @muscles[7].name %></h3>
		<p><%= @muscles[7].description %></p>
		<a>Click muscle group to read more...</a>
	</div>

app/views/musclegroups/show.html.erb
<style>
    body {
    background-color: #101010;
    background-image: none !important;
    }
</style>

<div class="container">  
  <h1 class="blue"><%= @muscle.name =%></h1>
  <h4><%= @muscle.description =%></h4>
  <br><br>

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#workouts" aria-controls="home" role="tab" data-toggle="tab">Workouts</a></li>
    <li role="presentation"><a href="#supps" aria-controls="profile" role="tab" data-toggle="tab">Supplements & Nutrition</a></li>
  </ul>

  <!-- tab contents -->
  <div class="tab-content">
      <div role="tabpanel" class="tab-pane active" id="workouts">
          <% @muscle.workouts.each do |workout| %>
            <div class="row">
              <div class="col-md-6">
                <h3><%= workout.name %></h3>
                <p class="grey"><%= workout.description %></p>
                <% if current_user %>
                  <a class="add-toggle" data-id="<%= workout.id %>">Add this workout to your schedule</a>
                  <div class="add-field add-field<%= workout.id %> animated fadeIn" data-toggle="0" hidden>
                    <select id="status-<%= workout.id %>" name="cars">
                      <option value="1">Sunday</option>
                      <option value="2">Monday</option>
                      <option value="3">Tuesday</option>
                      <option value="4">Wednesday</option>
                      <option value="5">Thursday</option>
                      <option value="6">Friday</option>
                      <option value="7">Saturday</option>
                    </select>
                    <button class="appt-submit" data-id="<%= current_user.id %>" data-workout="<%= workout.id %>">Submit</button>
                  </div>
                <% end %>
              </div>
              
              <div class="col-md-6">
                <iframe class="video" width="560" height="315" src="https://www.youtube.com/embed/<%= workout.video_url %>" frameborder="0" allowfullscreen></iframe>
              </div>
            </div>
            <br>
          <% end %>
      </div>

      <!-- Supplements & Nutrition -->
      <div role="tabpanel" class="tab-pane" id="supps">
        <div class="row">
          <div class="col-md-6">
            <h2 class="blue">Supplements</h2>
            <% @muscle.supplements.each do |supplements| %>
              <h3><%= supplements.name %></h3>
              <p class="grey"><%= supplements.description %></p>
            <% end %>
          </div>
          <div class="col-md-6">
            <h2 class="blue">Nutrition</h2>
            <% @muscle.foods.each do |workout| %>
              <h3><%= workout.name %></h3>
              <p class="grey"><%= workout.description %></p>
            <% end %>
          </div>
        </div>
      </div>

</div>